version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.3.1

workflows:
  test-deploy:
    jobs:
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/
      - orb-tools/pack:
          filters:
            tags:
              only: /.*/
      - orb-tools/publish:
          orb_name: nexbus/static-website
          vcs_type: <<pipeline.project.type>>
          pub_type: production
          requires: [orb-tools/lint, orb-tools/pack]
          context: orb-publishing
          enable_pr_comment: false
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
